[keyboard]
name = "rmk_pat"
product_name = "rmk_pat"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "rmk"
board = "nice!nano_v2"

[layout]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true
rows = 4
cols = 10
layers = 1
keymap = [
    [
        ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
        ["Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "Kc6", "Kc7", "Kc8", "Kc9", "Kc0"],
        ["K", "L", "M", "N", "O", "P", "Q", "R", "S", "T"],
        ["No", "No", "No", "U", "V", "W", "X", "No", "No", "No"],
    ],
]

[storage]

[ble]
enabled = true

[behavior]
enable_hrm = true

[split]
connection = "ble"

[split.central]
rows = 4
cols = 5
row_offset = 0
col_offset = 0
ble_addr = [0x18, 0xe2, 0x21, 0x80, 0xc0, 0xc7]
[split.central.matrix]
# nice!nano pins (https://nicekeyboards.com/docs/nice-nano/pinout-schematic) to 
# cols & rows (https://docs.splitkb.com/product-guides/aurora-series/schematics/aurora-sweep) 
# left pins
# P1_06 = col0
# P1_04 = col1
# P0_11 = col2
# P1_00 = col3
# P0_24 = col4
# right pins
# P0_02 = row2
# P1_15 = row1
# P1_13 = row0
# P1_11 = row3
input_pins = ["P0_02", "P1_15", "P1_13", "P1_11"]
output_pins = ["P1_06", "P1_04", "P0_11", "P1_00", "P0_24"]
direct_pin_low_active = true

[[split.peripheral]]
rows = 4
cols = 5
row_offset = 0
col_offset = 5
ble_addr = [0x7e, 0xfe, 0x73, 0x9e, 0x66, 0xe3]
[split.peripheral.matrix]
input_pins = ["P0_02", "P1_15", "P1_13", "P1_11"]
output_pins = ["P1_06", "P1_04", "P0_11", "P1_00", "P0_24"]
direct_pin_low_active = true

# [[split.peripheral]]
# rows = 2
# cols = 1
# row_offset = 2
# col_offset = 2
# serial = [{ instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" }]
# input_pins = ["PIN_9", "PIN_11"]
# output_pins = ["PIN_10"]
